debug: false

logging.level:
  liquibase: info
  io.micrometer.prometheus: info
  org.springframework.batch: info
  org.springframework.cloud.task: debug
  org.springframework.jdbc: info
  com.broadcom.springconsulting: warn

spring:
  application:
    name: batch-demo
    org: spring-consulting

  batch:
    jdbc:
      initialize-schema: always    # always

  cloud:
    task:
      name: ${spring.application.name}
      external-execution-id: ${spring.application.name}
      closecontext-enabled: true

management:
  prometheus:
    metrics:
      export:
        enabled: true
        rsocket:
          enabled: true

micrometer.prometheus.rsocket:
  host: spring-cloud-dataflow-prometheus-proxy.dataflow.svc.cluster.local  #required
  port: 7001
  max-retries: 10000 # default is Long.MAX_VALUE
  first-backoff: 10s
  max-backoff: 10m