package com.broadcom.springconsulting.batch_demo.healthrankings.countrymeasure.exception;

public class CountryCodeRequiredCountryMeasureProcessorException extends CountryMeasureProcessorException {
}
