package com.broadcom.springconsulting.batch_demo.healthrankings.countymeasure.exception;

public class NotCountyMeasureRecordCountyMeasureProcessorException extends CountyMeasureProcessorException {
}
